services:

  nodevite-container:
    build:
      context: .
      dockerfile: docker/node-vite/Dockerfile
    volumes:
      - ./public:/app/public
      - node-modules-volume:/app/node_modules
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - IS_CONTAINER=TRUE
    networks:
      - app-network

  nginx-container:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node-modules-volume: